"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase/client";
import {PayoutRequestForm} from "@/components/account/PayoutRequestForm";
import {TeamInbox} from "@/components/account/TeamInbox";
type EventRow={id:string;name:string;slug:string;archived:boolean};
type Dashboard={profile?:{full_name?:string;public_profile?:boolean};stats?:{uploaded:number;sold:number;revenue:number;commission:number;paid:number;pending:number;goal:number};payouts?:Array<{id:string;commission_amount:number;status:string;period_start?:string;period_end?:string;receipt_url?:string}>;requests?:Array<{id:string;amount:number;status:string}>;notifications?:Array<{id:string;title:string;body?:string;href?:string}>};
const money=(value=0)=>`R$ ${Number(value).toFixed(2).replace(".",",")}`;
export default function PhotographerPage(){
 const[events,setEvents]=useState<EventRow[]>([]),[eventId,setEventId]=useState(""),[files,setFiles]=useState<File[]>([]),[category,setCategory]=useState("Geral"),[running,setRunning]=useState(false),[paused,setPaused]=useState(false),[message,setMessage]=useState(""),[progress,setProgress]=useState(0),[dashboard,setDashboard]=useState<Dashboard>({}); const pausedRef=useRef(false);
 useEffect(()=>{void Promise.all([fetch("/api/photographer/events").then(r=>r.json()).then(d=>setEvents((d.events||[]).flat())),fetch("/api/photographer/dashboard").then(r=>r.json()).then(setDashboard)]).catch(()=>setMessage("Não foi possível carregar o portal."));},[]);
 async function upload(){if(!eventId||!files.length)return setMessage("Selecione o evento e as fotos.");setRunning(true);setPaused(false);pausedRef.current=false;let done=0,skipped=0;try{for(const file of files){while(pausedRef.current)await new Promise(resolve=>setTimeout(resolve,300));setMessage(`Preparando ${done+skipped+1} de ${files.length}: ${file.name}`);const hash=await crypto.subtle.digest("SHA-256",await file.arrayBuffer());const checksum=Array.from(new Uint8Array(hash),byte=>byte.toString(16).padStart(2,"0")).join("");const prepare=await fetch(`/api/photographer/events/${eventId}/photos-direct`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({size:file.size,type:file.type,checksum})});const signed=await prepare.json();if(prepare.status===409){skipped++;setProgress(Math.round((done+skipped)/files.length*100));continue}if(!prepare.ok)throw new Error(signed.error);const{error}=await createClient().storage.from("originals").uploadToSignedUrl(signed.path,signed.token,file,{contentType:file.type});if(error)throw error;const finish=await fetch(`/api/photographer/events/${eventId}/photos-direct`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({path:signed.path,checksum,category})});const result=await finish.json();if(!finish.ok)throw new Error(result.error);done++;setProgress(Math.round((done+skipped)/files.length*100));}setMessage(`${done} fotos enviadas; ${skipped} duplicadas ignoradas.`);setFiles([]);}catch(error){setMessage(`${done} enviadas. ${error instanceof Error?error.message:"Erro no envio."}`)}finally{setRunning(false);setPaused(false);pausedRef.current=false}}
 const stats=dashboard.stats; const payoutRequest=stats&&stats.pending>0?<PayoutRequestForm available={stats.pending}/>:<section className="mt-8 rounded-xl border border-neutral-800 bg-neutral-950 p-5"><h2 className="font-black">Solicitar repasse</h2><p className="mt-2 text-sm text-neutral-400">Você ainda não possui saldo disponível para solicitar.</p></section>;
 return <main className="min-h-screen bg-black px-4 pb-24 pt-28 text-white sm:px-6"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-red-500">Área da equipe</p><h1 className="text-4xl font-black">Portal do fotógrafo</h1><p className="mt-2 text-neutral-400">Olá, {dashboard.profile?.full_name||"fotógrafo"}. Seus eventos, envios e repasses em um só lugar.</p></div>{dashboard.profile?.public_profile&&<Link href="/minha-conta" className="rounded-lg border border-neutral-700 px-4 py-3">Gerenciar minha conta</Link>}</div>{payoutRequest}
 {stats&&<><section className="my-8 grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-6">{[["Publicadas",stats.uploaded],["Vendidas",stats.sold],["Receita",money(stats.revenue)],["Comissão",money(stats.commission)],["Recebido",money(stats.paid)],["A receber",money(stats.pending)]].map(([label,value])=><div key={label} className="rounded-xl border border-neutral-800 bg-neutral-900 p-4"><p className="text-xs text-neutral-500">{label}</p><p className="mt-1 text-xl font-black">{value}</p></div>)}</section><section className="mb-8 rounded-xl border border-neutral-800 bg-neutral-900 p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-black">Meta financeira mensal</h2><span className="text-sm text-neutral-300">{money(stats.commission)} / {money(stats.goal)}</span></div><div className="mt-3 h-3 overflow-hidden rounded-full bg-neutral-800"><div className="h-full rounded-full bg-red-600 transition-all" style={{width:`${stats.goal>0?Math.min(100,(stats.commission/stats.goal)*100):0}%`}}/></div>{stats.goal<=0&&<p className="mt-2 text-sm text-neutral-500">Defina sua meta em Minha conta → Editar perfil.</p>}</section></>}
 <TeamInbox notifications={dashboard.notifications||[]} requests={dashboard.requests||[]}/>
 <div className="grid gap-7 lg:grid-cols-[1.4fr_1fr]"><section className="space-y-5 rounded-xl border border-neutral-800 bg-neutral-900 p-6"><h2 className="text-2xl font-bold">Enviar fotos</h2><label className="block">Evento<select value={eventId} onChange={e=>setEventId(e.target.value)} className="mt-2 w-full rounded bg-black p-3"><option value="">Selecione</option>{events.filter(e=>!e.archived).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label className="block">Categoria / área<input value={category} onChange={e=>setCategory(e.target.value)} maxLength={60} placeholder="Ex.: Pista, Boxes, Premiação" className="mt-2 w-full rounded bg-black p-3"/></label><label className="block">Fotos<input type="file" multiple accept="image/*" disabled={running} onChange={e=>setFiles(Array.from(e.target.files||[]))} className="mt-2 block w-full"/></label><p className="text-sm text-neutral-400">{files.length} fotos selecionadas · duplicadas são ignoradas automaticamente</p>{running&&<><div className="h-3 overflow-hidden rounded bg-neutral-800"><div className="h-full bg-red-600 transition-all" style={{width:`${progress}%`}}/></div><button type="button" onClick={()=>setPaused(v=>{pausedRef.current=!v;return !v})} className="rounded border border-neutral-600 px-4 py-2">{paused?"Continuar":"Pausar após o arquivo atual"}</button></>}<button type="button" disabled={running} onClick={upload} className="w-full rounded bg-red-600 py-3 font-bold disabled:opacity-50">{running?`${progress}% enviado`:"Enviar fotos"}</button>{message&&<p className="rounded bg-black p-3 text-sm" aria-live="polite">{message}</p>}</section>
 <section className="rounded-xl border border-neutral-800 bg-neutral-900 p-6"><h2 className="text-2xl font-bold">Histórico de repasses</h2><div className="mt-5 space-y-3">{(dashboard.payouts||[]).map(p=><article key={p.id} className="rounded-lg bg-black p-4"><div className="flex justify-between gap-3"><b>{money(p.commission_amount)}</b><span className={p.status==="paid"?"text-green-400":"text-amber-400"}>{p.status==="paid"?"Pago":"Pendente"}</span></div><p className="mt-1 text-xs text-neutral-500">{p.period_start||"Período aberto"} — {p.period_end||"atual"}</p>{p.receipt_url&&<a href={p.receipt_url} target="_blank" rel="noreferrer" className="mt-2 inline-block text-sm underline">Ver comprovante</a>}</article>)}{!dashboard.payouts?.length&&<p className="text-neutral-400">Nenhum repasse registrado ainda.</p>}</div></section></div></div></main>;
}
