export const STUDIO_CONTRACT_CLAUSES=[
 ["1. Objeto","A CONTRATADA prestará os serviços fotográficos descritos na proposta aceita, respeitando categoria, pacote, data, duração, local, quantidade estimada de imagens e demais condições registradas no sistema."],
 ["2. Obrigações da contratada","A M&M realizará o serviço com diligência técnica e artística, manterá comunicação sobre o andamento, selecionará e editará as imagens conforme sua identidade visual e entregará o material pelo meio e prazo definidos na proposta."],
 ["3. Obrigações do contratante","O CONTRATANTE fornecerá informações corretas, permissões de acesso, pontualidade, condições seguras de trabalho e os pagamentos nos vencimentos. Atrasos do evento podem reduzir o tempo útil de cobertura sem alterar o valor contratado."],
 ["4. Preço e pagamento","A reserva da data ocorre após aceite e pagamento do sinal indicado. O saldo deverá ser quitado até a data registrada na proposta ou antes da liberação dos arquivos finais. Taxas do meio de pagamento e adicionais autorizados poderão integrar o saldo."],
 ["5. Remarcação e cancelamento","Pedidos de remarcação dependem de disponibilidade. O sinal compensa a reserva da agenda e custos preparatórios, observada a legislação aplicável. Em caso de força maior, as partes buscarão nova data ou solução proporcional ao serviço já executado."],
 ["6. Seleção, edição e entrega","A curadoria e o tratamento seguem o estilo da M&M. Arquivos brutos não integram a contratação salvo previsão expressa. O prazo começa após a realização do serviço e, quando aplicável, após a seleção do cliente e quitação do saldo."],
 ["7. Galeria e guarda","A galeria privada permanecerá disponível pelo período informado. O CONTRATANTE deverá baixar e manter cópia dos arquivos antes do vencimento. Após esse período, a guarda não é garantida, embora possa ser prorrogada por acordo."],
 ["8. Direitos autorais e imagem","Os direitos autorais permanecem com os fotógrafos e a M&M. O cliente recebe licença pessoal de uso das imagens entregues. Publicação promocional pela M&M dependerá da autorização aplicável, que poderá ser registrada ou revogada para usos futuros."],
 ["9. Privacidade e LGPD","Dados pessoais serão tratados para orçamento, execução, pagamento, entrega, suporte e obrigações legais, conforme a Política de Privacidade. O titular poderá exercer seus direitos pelos canais oficiais da M&M."],
 ["10. Aceite eletrônico e foro","O aceite eletrônico registra nome, data, IP e versão do documento, produzindo evidência da manifestação de vontade. As partes buscarão solução amigável; permanecendo conflito, aplica-se o foro legalmente competente, respeitados os direitos do consumidor."],
] as const;

export const PHOTOGRAPHER_CONTRACT_CLAUSES=[
 ["1. Objeto","O PROFISSIONAL atuará em trabalhos indicados pela M&M conforme escala aceita, função, local, duração, remuneração e orientações registradas para cada serviço, sem exclusividade automática."],
 ["2. Disponibilidade e conduta","A confirmação de escala implica compromisso de pontualidade, apresentação adequada, respeito ao cliente e à equipe, comunicação imediata de impedimentos e observância das regras de segurança do local."],
 ["3. Padrão técnico M&M","O PROFISSIONAL seguirá briefing, formato de captura, redundância, identificação das mídias, preservação dos metadados e orientações artísticas e operacionais da M&M, sem prometer entregas ou valores diretamente ao cliente."],
 ["4. Arquivos e entrega","Todo material do trabalho deverá ser entregue no prazo e meio definidos, íntegro e sem retenção de cópias que exponham clientes. A perda evitável de arquivos ou o descumprimento grave será apurado conforme responsabilidade comprovada."],
 ["5. Remuneração e repasse","A remuneração será a comissão fixa ou percentual registrada na escala. O repasse observará recebimento do cliente, conclusão das etapas atribuídas e conferência administrativa. Despesas exigem autorização prévia."],
 ["6. Sigilo e LGPD","Dados, conversas, imagens não publicadas, preços e informações internas são confidenciais. O PROFISSIONAL tratará dados somente para executar o trabalho, usando acessos individuais e comunicando incidentes imediatamente."],
 ["7. Direitos autorais e portfólio","A autoria moral é preservada. O uso em portfólio pessoal depende de publicação/autorização da M&M e do cliente quando exigida. Não é permitido comercializar, ceder ou publicar arquivos brutos ou material confidencial."],
 ["8. Equipamentos e segurança","Salvo ajuste escrito, o PROFISSIONAL responde pelos próprios equipamentos e rotinas de backup durante sua atuação. Nenhuma orientação exige exposição a risco indevido; ocorrências devem ser comunicadas."],
 ["9. Natureza e encerramento","Cada escala constitui prestação autônoma específica, sem garantia de volume mínimo. Qualquer parte pode encerrar futuras colaborações, preservando trabalhos confirmados, valores devidos, sigilo e obrigações sobre dados e arquivos."],
 ["10. Aceite eletrônico","O aceite registra identidade, data, IP e versão. Alterações relevantes exigirão nova versão ou termo complementar. As partes buscarão solução amigável antes das medidas cabíveis."],
] as const;

export function contractSnapshot(input:{type:"studio"|"photographer";clientName?:string;clientEmail?:string;clientWhatsapp?:string;photographerName?:string;service?:string;packageName?:string;eventDate?:string;city?:string;venue?:string;guests?:number;notes?:string;budget?:number;total?:number;deposit?:number;deliveryDays?:number}){
 return{version:"2026.08",type:input.type,brand:"M&M Fotografias",generatedAt:new Date().toISOString(),parties:input.type==="studio"?{contractor:"M&M Fotografias",client:input.clientName||"CONTRATANTE",email:input.clientEmail||null,whatsapp:input.clientWhatsapp||null}:{contractor:"M&M Fotografias",professional:input.photographerName||"PROFISSIONAL"},service:{category:input.service||"Serviço fotográfico",package:input.packageName||"Conforme proposta",eventDate:input.eventDate||null,city:input.city||null,venue:input.venue||null,guests:Number(input.guests||0)||null,notes:input.notes||null,budget:Number(input.budget||0)||null,total:Number(input.total||0),deposit:Number(input.deposit||0),deliveryDays:Number(input.deliveryDays||30)},clauses:(input.type==="studio"?STUDIO_CONTRACT_CLAUSES:PHOTOGRAPHER_CONTRACT_CLAUSES).map(([title,text])=>({title,text}))}
}
