"use client";
import {useState} from "react";
type Photo={id:string;filename:string;url:string;downloadUrl?:string;selected:boolean};
export function PrivateGallery({galleryId,token,photos,allowSelection,allowDownload}:{galleryId:string;token:string;photos:Photo[];allowSelection:boolean;allowDownload:boolean}){
 const[items,setItems]=useState(photos),[open,setOpen]=useState<number|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 async function select(photo:Photo){const selected=!photo.selected;setItems(rows=>rows.map(row=>row.id===photo.id?{...row,selected}:row));const r=await fetch(`/api/galleries/${galleryId}/selection`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,photoId:photo.id,selected})});if(!r.ok){setItems(rows=>rows.map(row=>row.id===photo.id?{...row,selected:!selected}:row));setMessage("Não foi possível salvar a seleção.")}else setMessage(selected?"Foto selecionada.":"Foto removida da seleção.")}
 async function finalize(){if(!items.some(p=>p.selected)||!confirm("Finalizar e avisar a equipe sobre estas favoritas?"))return;setBusy(true);const r=await fetch(`/api/galleries/${galleryId}/selection`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,finalize:true})}),d=await r.json();setMessage(r.ok?`Seleção enviada: ${d.count} foto(s).`:d.error);setBusy(false)}
 const current=open===null?null:items[open];
 return <><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><p className="text-neutral-400">{items.length} fotos · {items.filter(p=>p.selected).length} favoritas selecionadas</p><div className="flex items-center gap-3">{allowSelection&&<button disabled={busy||!items.some(p=>p.selected)} onClick={finalize} className="rounded-xl bg-red-600 px-4 py-3 font-black disabled:opacity-40">Finalizar seleção</button>}{message&&<p className="text-sm text-green-400" aria-live="polite">{message}</p>}</div></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{items.map((photo,index)=><article key={photo.id} className={`overflow-hidden rounded-xl border bg-neutral-950 ${photo.selected?"border-red-500":"border-neutral-800"}`}><button onClick={()=>setOpen(index)} className="block aspect-square w-full overflow-hidden"><img src={photo.url} alt={photo.filename} draggable={false} className="h-full w-full object-cover transition hover:scale-105" onContextMenu={e=>e.preventDefault()}/></button><div className="flex items-center justify-between gap-2 p-3"><span className="truncate text-xs text-neutral-400">{photo.filename}</span>{allowSelection&&<button onClick={()=>select(photo)} className={`shrink-0 rounded-lg px-3 py-2 text-sm font-bold ${photo.selected?"bg-red-600":"bg-neutral-800"}`}>{photo.selected?"✓ Escolhida":"Escolher"}</button>}</div></article>)}</div>{current&&<div role="dialog" aria-modal="true" className="fixed inset-0 z-[200] grid place-items-center bg-black/95 p-3" onClick={()=>setOpen(null)}><button className="absolute right-4 top-4 rounded-full bg-white px-4 py-2 font-black text-black" onClick={()=>setOpen(null)}>✕</button><button disabled={open===0} onClick={e=>{e.stopPropagation();setOpen(v=>Math.max(0,(v||0)-1))}} className="absolute left-3 top-1/2 rounded-full bg-white/90 px-4 py-3 text-2xl text-black disabled:opacity-20">‹</button><img src={current.url} alt={current.filename} onClick={e=>e.stopPropagation()} onContextMenu={e=>e.preventDefault()} className="max-h-[82vh] max-w-[90vw] object-contain"/><button disabled={open===items.length-1} onClick={e=>{e.stopPropagation();setOpen(v=>Math.min(items.length-1,(v||0)+1))}} className="absolute right-3 top-1/2 rounded-full bg-white/90 px-4 py-3 text-2xl text-black disabled:opacity-20">›</button><div className="absolute bottom-4 flex gap-2"><button onClick={e=>{e.stopPropagation();void select(current)}} className="rounded-xl bg-red-600 px-5 py-3 font-black">{current.selected?"✓ Selecionada":"Selecionar favorita"}</button>{allowDownload&&current.downloadUrl&&<a onClick={e=>e.stopPropagation()} href={current.downloadUrl} className="rounded-xl bg-white px-5 py-3 font-black text-black">Baixar original</a>}</div></div>}</>;
}
