"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import type { RealtimeChannel } from "@supabase/supabase-js";
type Person={id:string;full_name?:string;email:string};
type Message={id:string;channel?:string;sender_id:string;body:string;read_at?:string|null;created_at:string;profiles?:{full_name?:string;email?:string}|Array<{full_name?:string;email?:string}>;pending?:boolean};
type QuickReply={id:string;title:string;body:string};

export function ChatPanel({staff=false,initialMode,initialOther}:{staff?:boolean;initialMode?:string;initialOther?:string}){
 const allowedModes=["team","management","direct","support"],[mode,setMode]=useState(allowedModes.includes(initialMode||"")?initialMode!:staff?"team":"support"),[other,setOther]=useState(initialOther||""),[people,setPeople]=useState<Person[]>([]),[quickReplies,setQuickReplies]=useState<QuickReply[]>([]),[messages,setMessages]=useState<Message[]>([]),[me,setMe]=useState(""),[roles,setRoles]=useState<string[]>([]),[channelName,setChannelName]=useState(""),[draft,setDraft]=useState(""),[error,setError]=useState(""),[typing,setTyping]=useState(""),[online,setOnline]=useState(0),[connected,setConnected]=useState(false);
 const bottom=useRef<HTMLDivElement>(null),typingTimer=useRef<ReturnType<typeof setTimeout>|null>(null),roomRef=useRef<RealtimeChannel|null>(null),management=roles.some(role=>["owner","admin","support"].includes(role)),needsPerson=mode==="direct"||(staff&&mode==="support");
 const load=useCallback(async()=>{const r=await fetch(`/api/chat?mode=${mode}&other=${other}`,{cache:"no-store"}),d=await r.json();setPeople(d.people||[]);setQuickReplies(d.quickReplies||[]);setMe(d.me||"");setRoles(d.roles||[]);setChannelName(d.channel||"");if(r.ok){setMessages(d.messages||[]);setError("")}else setError(d.error||"Erro no chat")},[mode,other]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{const list=bottom.current?.parentElement;if(list)list.scrollTo({top:list.scrollHeight,behavior:"smooth"})},[messages]);
 useEffect(()=>{if(!channelName)return;const supabase=createClient(),room=supabase.channel(`chat:${channelName}`,{config:{presence:{key:me}}}).on("postgres_changes",{event:"*",schema:"public",table:"chat_messages",filter:`channel=eq.${channelName}`},()=>void load()).on("broadcast",{event:"typing"},({payload}:{payload:{user?:string;name?:string}})=>{if(payload.user!==me){setTyping(payload.name||"Alguém");if(typingTimer.current)clearTimeout(typingTimer.current);typingTimer.current=setTimeout(()=>setTyping(""),1500)}}).on("presence",{event:"sync"},()=>setOnline(Object.keys(room.presenceState()).length)).subscribe((status:string)=>{setConnected(status==="SUBSCRIBED");if(status==="SUBSCRIBED")void room.track({online_at:new Date().toISOString()})});roomRef.current=room;return()=>{roomRef.current=null;if(typingTimer.current)clearTimeout(typingTimer.current);void supabase.removeChannel(room)}},[channelName,load,me]);
 async function send(e:React.FormEvent){e.preventDefault();const text=draft.trim();if(!text)return;setDraft("");const temp=`temp-${Date.now()}`;setMessages(current=>[...current,{id:temp,sender_id:me,body:text,created_at:new Date().toISOString(),pending:true,profiles:{full_name:"Você"}}]);const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode,other,body:text})}),d=await r.json();if(r.ok)setMessages(current=>current.map(item=>item.id===temp?d.message:item));else{setMessages(current=>current.filter(item=>item.id!==temp));setDraft(text);setError(d.error||"Não foi possível enviar")}}
 function choose(next:string){setMode(next);setOther("");setMessages([]);setChannelName("")}
 function changed(value:string){setDraft(value);if(roomRef.current)void roomRef.current.send({type:"broadcast",event:"typing",payload:{user:me,name:"Alguém"}})}
 const tab=(value:string,label:string)=><button type="button" onClick={()=>choose(value)} className={`rounded-lg px-4 py-2 ${mode===value?"bg-red-700":"bg-black"}`}>{label}</button>;
 return <section className="min-w-0 overflow-hidden rounded-2xl border border-neutral-800 bg-neutral-900"><div className="flex flex-wrap items-center gap-2 border-b border-neutral-800 p-3 sm:p-4">{staff?<>{tab("team","Grupo da equipe")}{management&&tab("management","Gestão privada")}{tab("direct","Individual")}{management&&tab("support","Atendimento")}</>:<>{tab("support","Falar com atendimento")}{tab("direct","Falar com fotógrafo")}</>}{needsPerson&&<select value={other} onChange={e=>setOther(e.target.value)} className="min-w-0 basis-full rounded-lg bg-black p-2 sm:flex-1"><option value="">Selecione uma pessoa</option>{people.map(p=><option key={p.id} value={p.id}>{p.full_name||p.email}</option>)}</select>}<span className={`text-xs sm:ml-auto ${connected?"text-green-400":"text-amber-400"}`}>{connected?`● Tempo real${online>1?` · ${online} online`:""}`:"Conectando…"}</span></div><div className="h-[min(55vh,520px)] space-y-3 overflow-y-auto overscroll-contain p-3 sm:p-4">{messages.map(item=>{const profile=Array.isArray(item.profiles)?item.profiles[0]:item.profiles,own=item.sender_id===me;return <div key={item.id} className={`max-w-[92%] break-words rounded-2xl p-3 sm:max-w-[85%] ${own?"ml-auto bg-red-700":"bg-black"}`}><b className="text-xs">{own?"Você":profile?.full_name||profile?.email||"Equipe"}</b><p className="mt-1 whitespace-pre-wrap">{item.body}</p><div className="mt-1 flex justify-end gap-2 text-[10px] text-neutral-300"><time>{new Date(item.created_at).toLocaleString("pt-BR")}</time>{own&&<span>{item.pending?"Enviando…":item.read_at?"✓✓ Lida":"✓ Enviada"}</span>}</div></div>})}{!messages.length&&<p className="text-center text-neutral-500">{needsPerson&&!other?"Selecione uma pessoa para conversar.":"Nenhuma mensagem ainda."}</p>}<div ref={bottom}/></div><div className="min-h-5 px-4 text-xs text-neutral-400">{typing&&`${typing} está digitando…`}</div>{management&&mode==="support"&&quickReplies.length>0&&<div className="flex gap-2 overflow-x-auto px-3 pb-2 sm:px-4">{quickReplies.map(reply=><button key={reply.id} type="button" title={reply.body} onClick={()=>setDraft(reply.body)} className="shrink-0 rounded-full border border-neutral-700 bg-black px-3 py-1.5 text-xs hover:border-red-500">{reply.title}</button>)}</div>}<form onSubmit={send} className="flex gap-2 border-t border-neutral-800 p-3 sm:p-4"><input value={draft} onChange={e=>changed(e.target.value)} maxLength={2000} className="min-w-0 flex-1 rounded-xl bg-black p-3" placeholder="Digite sua mensagem…"/><button disabled={!draft.trim()||(needsPerson&&!other)} className="rounded-xl bg-red-600 px-4 font-bold disabled:opacity-40 sm:px-5">Enviar</button></form>{error&&<p className="px-4 pb-3 text-sm text-red-400">{error}</p>}</section>}
