import { supabaseAdmin } from "@/lib/supabaseAdmin";
import { orderPhotos } from "@/lib/orders";

function money(value: number) { return value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" }); }

export default async function FinancePage() {
  const { data: orders } = await supabaseAdmin.from("orders").select("id,total,discount_amount,photos,created_at,email").eq("status", "paid").order("created_at");
  const paid = orders || []; const revenue = paid.reduce((sum, order) => sum + Number(order.total || 0), 0); const discounts = paid.reduce((sum, order) => sum + Number(order.discount_amount || 0), 0); const photoCount = paid.reduce((sum, order) => sum + orderPhotos(order.photos).length, 0); const ticket = paid.length ? revenue / paid.length : 0;
  const monthly = new Map<string, { revenue: number; orders: number }>();
  for (const order of paid) { const key = new Date(order.created_at).toLocaleDateString("pt-BR", { month: "short", year: "2-digit" }); const row = monthly.get(key) || { revenue: 0, orders: 0 }; row.revenue += Number(order.total || 0); row.orders += 1; monthly.set(key, row); }
  const months = [...monthly.entries()].slice(-12); const max = Math.max(1, ...months.map(([, row]) => row.revenue));
  const customers = new Map<string, number>(); paid.forEach(order => customers.set(order.email, (customers.get(order.email) || 0) + Number(order.total || 0)));
  return <main className="min-h-screen bg-black px-6 pb-20 pt-32 text-white"><div className="mx-auto max-w-6xl"><h1 className="mb-8 text-4xl font-bold">Painel financeiro</h1><div className="grid gap-4 md:grid-cols-4"><Metric label="Faturamento" value={money(revenue)} /><Metric label="Ticket médio" value={money(ticket)} /><Metric label="Pedidos pagos" value={String(paid.length)} /><Metric label="Fotos vendidas" value={String(photoCount)} /></div><p className="mt-4 text-sm text-neutral-400">Descontos concedidos: {money(discounts)}</p><section className="mt-8 rounded-xl border border-neutral-800 bg-neutral-900 p-6"><h2 className="mb-6 text-xl font-bold">Últimos 12 meses com vendas</h2><div className="space-y-4">{!months.length && <p className="text-neutral-400">Ainda não há vendas confirmadas.</p>}{months.map(([month, row]) => <div key={month} className="grid grid-cols-[80px_1fr_auto] items-center gap-4"><span>{month}</span><div className="h-4 overflow-hidden rounded bg-neutral-800"><div className="h-full rounded bg-red-600" style={{ width: `${Math.max(3, row.revenue / max * 100)}%` }} /></div><span className="text-right">{money(row.revenue)} · {row.orders}</span></div>)}</div></section><section className="mt-8 rounded-xl border border-neutral-800 bg-neutral-900 p-6"><h2 className="mb-4 text-xl font-bold">Clientes por faturamento</h2>{[...customers.entries()].sort((a,b) => b[1]-a[1]).slice(0,10).map(([email, total]) => <div key={email} className="flex justify-between border-b border-neutral-800 py-3 last:border-0"><span>{email}</span><b>{money(total)}</b></div>)}</section></div></main>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-neutral-800 bg-neutral-900 p-5"><p className="text-neutral-400">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>; }
