"use client";
import {useState} from "react";
import {useCart} from "@/context/CartContext";
import {PhotoCard} from "@/components/ui/PhotoCard";
import {SafeImage} from "@/components/ui/SafeImage";

export default function FavoritesPage(){
 const{favorites,recent,items,addToCart}=useCart(),[tab,setTab]=useState<"favorites"|"recent">("favorites"),[compare,setCompare]=useState<string[]>([]),photos=tab==="favorites"?favorites:recent,missing=favorites.filter(photo=>!items.some(item=>item.id===photo.id)),chosen=favorites.filter(photo=>compare.includes(photo.id));
 const toggleCompare=(id:string)=>setCompare(current=>current.includes(id)?current.filter(item=>item!==id):current.length<3?[...current,id]:current);
 const groups=Object.entries(photos.reduce<Record<string,typeof photos>>((result,photo)=>{const key=photo.evento||"Outras fotos";(result[key]||=[]).push(photo);return result},{}));
 return <main className="min-h-screen bg-black px-4 pb-24 pt-28 text-white sm:px-6 sm:pt-32"><div className="mx-auto max-w-6xl">
  <div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold sm:text-4xl">Minha biblioteca</h1><p className="mt-2 text-neutral-400">Suas escolhas acompanham sua conta em todos os aparelhos.</p></div>{favorites.length>0&&<button type="button" disabled={!missing.length} onClick={()=>missing.forEach(addToCart)} className="rounded-lg bg-red-600 px-5 py-3 font-bold disabled:bg-neutral-700">{missing.length?`Adicionar ${missing.length} ao carrinho`:"Todas no carrinho ✓"}</button>}</div>
  <div className="my-6 flex flex-wrap gap-2"><button onClick={()=>setTab("favorites")} className={`rounded-lg px-4 py-3 font-bold ${tab==="favorites"?"bg-red-600":"bg-neutral-900"}`}>Favoritos ({favorites.length})</button><button onClick={()=>setTab("recent")} className={`rounded-lg px-4 py-3 font-bold ${tab==="recent"?"bg-red-600":"bg-neutral-900"}`}>Vistos recentemente ({recent.length})</button>{compare.length>0&&<button onClick={()=>setCompare([])} className="rounded-lg border border-neutral-700 px-4 py-3">Limpar comparação</button>}</div>
  {!photos.length?<p className="rounded-xl border border-neutral-800 bg-neutral-900 p-6 text-neutral-400">{tab==="favorites"?"Você ainda não favoritou nenhuma foto. Use o coração nas galerias para montar sua seleção.":"As fotos ampliadas recentemente aparecerão aqui."}</p>:<div className="space-y-10">{groups.map(([event,eventPhotos])=><section key={event}><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-black sm:text-2xl">{event}</h2><span className="rounded-full bg-neutral-900 px-3 py-1 text-sm text-neutral-400">{eventPhotos.length} foto(s)</span></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4 md:gap-4">{eventPhotos.map(photo=><div key={photo.id} className="min-w-0"><PhotoCard photo={photo}/>{tab==="favorites"&&<button type="button" onClick={()=>toggleCompare(photo.id)} className={`mt-2 w-full rounded-lg px-3 py-2 text-sm font-bold ${compare.includes(photo.id)?"bg-red-700":"bg-neutral-900"}`}>{compare.includes(photo.id)?"✓ Comparando":"Comparar"}</button>}</div>)}</div></section>)}</div>}
  {chosen.length>0&&<aside className="fixed inset-x-3 bottom-[calc(5rem+env(safe-area-inset-bottom))] z-[110] rounded-2xl border border-neutral-700 bg-neutral-950/95 p-3 shadow-2xl backdrop-blur lg:bottom-4 lg:left-auto lg:right-4 lg:w-[min(900px,calc(100vw-2rem))]"><div className="mb-2 flex items-center justify-between"><b>Comparação ({chosen.length}/3)</b><button onClick={()=>setCompare([])} aria-label="Fechar comparação" className="text-2xl">×</button></div><div className={`grid gap-2 ${chosen.length===1?"grid-cols-1":chosen.length===2?"grid-cols-2":"grid-cols-3"}`}>{chosen.map(photo=><div key={photo.id} className="min-w-0"><div className="relative aspect-square overflow-hidden rounded-lg"><SafeImage src={photo.imagem} alt={`Foto ${photo.numero}`} fill className="object-contain" sizes="33vw"/></div><p className="mt-1 truncate text-center text-xs">#{photo.numero} · {photo.preco.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</p></div>)}</div></aside>}
 </div></main>
}
