import{NextResponse}from"next/server";import sharp from"sharp";import{isApiAdmin,getApiUser}from"@/lib/api-auth";import{supabaseAdmin}from"@/lib/supabaseAdmin";export const maxDuration=60;
const MAX=25*1024*1024;const slugify=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,80);
export async function GET(){if(!(await isApiAdmin()))return NextResponse.json({error:"Negado"},{status:403});const[{data:galleries},{data:jobs}]=await Promise.all([supabaseAdmin.from("service_galleries").select("*,service_gallery_photos(*)").order("created_at",{ascending:false}),supabaseAdmin.from("service_jobs").select("id,title,event_date,status").neq("status","cancelled").order("event_date")]);return NextResponse.json({galleries:galleries||[],jobs:jobs||[]})}
export async function POST(request:Request){if(!(await isApiAdmin()))return NextResponse.json({error:"Negado"},{status:403});const user=await getApiUser(),body=await request.json();
 if(body.kind==="create"){const jobId=String(body.jobId||""),{data:job}=await supabaseAdmin.from("service_jobs").select("id,title").eq("id",jobId).maybeSingle();if(!job)return NextResponse.json({error:"Trabalho não encontrado."},{status:404});const slug=`${slugify(String(body.slug||job.title))}-${crypto.randomUUID().slice(0,6)}`;const{data,error}=await supabaseAdmin.from("service_galleries").insert({job_id:job.id,title:String(body.title||job.title).slice(0,160),slug,welcome_text:String(body.welcomeText||"Suas fotos estão prontas. Selecione suas favoritas e acompanhe a entrega."),published:Boolean(body.published),allow_download:Boolean(body.allowDownload),allow_selection:body.allowSelection!==false,expires_at:body.expiresAt||null}).select("*").single();if(!error&&data)await supabaseAdmin.from("service_activity").insert({job_id:job.id,actor_id:user?.id,kind:"gallery_created",title:"Galeria privada criada",details:{galleryId:data.id},visible_to_client:true});return error?NextResponse.json({error:error.message},{status:400}):NextResponse.json({success:true,gallery:data})}
 if(body.kind==="prepare"){const size=Number(body.size),type=String(body.type||"");if(!type.startsWith("image/")||size<=0||size>MAX)return NextResponse.json({error:"Use imagens de até 25 MB."},{status:400});const{data:g}=await supabaseAdmin.from("service_galleries").select("id").eq("id",body.galleryId).maybeSingle();if(!g)return NextResponse.json({error:"Galeria inválida."},{status:404});const ext=type.includes("png")?"png":type.includes("webp")?"webp":"jpg",path=`${g.id}/${crypto.randomUUID()}.${ext}`,{data,error}=await supabaseAdmin.storage.from("service-galleries").createSignedUploadUrl(path);return error?NextResponse.json({error:error.message},{status:500}):NextResponse.json({path,token:data.token})}
 if(body.kind==="finish"){const path=String(body.path||""),galleryId=String(body.galleryId||"");if(!path.startsWith(`${galleryId}/`))return NextResponse.json({error:"Envio inválido."},{status:400});const{data:raw,error:readError}=await supabaseAdmin.storage.from("service-galleries").download(path);if(readError||!raw)return NextResponse.json({error:"Não foi possível processar a foto."},{status:500});const previewPath=`${galleryId}/previews/${crypto.randomUUID()}.jpg`,preview=await sharp(Buffer.from(await raw.arrayBuffer())).rotate().resize({width:1600,height:1600,fit:"inside",withoutEnlargement:true}).jpeg({quality:72,progressive:true}).toBuffer(),{error:previewError}=await supabaseAdmin.storage.from("service-galleries").upload(previewPath,preview,{contentType:"image/jpeg",upsert:false});if(previewError)return NextResponse.json({error:previewError.message},{status:500});const{data,error}=await supabaseAdmin.from("service_gallery_photos").insert({gallery_id:galleryId,storage_path:path,preview_path:previewPath,filename:String(body.filename||"foto.jpg").slice(0,180),sort_order:Number(body.sortOrder||0)}).select("id").single();return error?NextResponse.json({error:error.message},{status:400}):NextResponse.json({success:true,...data})}
 return NextResponse.json({error:"Ação inválida."},{status:400})}
export async function PATCH(request:Request){if(!(await isApiAdmin()))return NextResponse.json({error:"Negado"},{status:403});const body=await request.json(),allowed=["title","welcome_text","published","allow_download","allow_selection","expires_at"],update=Object.fromEntries(allowed.filter(k=>k in body).map(k=>[k,body[k]]));update.updated_at=new Date().toISOString();const{error}=await supabaseAdmin.from("service_galleries").update(update).eq("id",body.id);return error?NextResponse.json({error:error.message},{status:400}):NextResponse.json({success:true})}
