import { requireUser } from "@/lib/auth";
import { supabaseAdmin } from "@/lib/supabaseAdmin";
import { money, serviceBySlug } from "@/lib/service-catalog";

export default async function ContractsPage(){
 const user=await requireUser();
 const[{data:requests},{data:jobs}]=await Promise.all([supabaseAdmin.from("service_requests").select("*").eq("user_id",user.id).order("created_at",{ascending:false}),supabaseAdmin.from("service_jobs").select("*,service_job_tasks(*),service_job_files(*)").eq("client_user_id",user.id).order("event_date",{ascending:true})]);
 return <main className="min-h-screen bg-black px-4 pb-24 pt-32 text-white"><div className="mx-auto max-w-5xl"><p className="font-bold uppercase tracking-widest text-red-500">Portal do cliente</p><h1 className="mt-2 text-4xl font-black">Minhas contratações</h1><h2 className="mb-4 mt-10 text-2xl font-black">Trabalhos em andamento</h2><div className="grid gap-5">{jobs?.map(job=><article key={job.id} className="rounded-2xl border border-neutral-800 bg-neutral-950 p-6"><div className="flex flex-wrap justify-between gap-4"><div><h3 className="text-2xl font-black">{job.title}</h3><p className="text-neutral-400">{job.event_date?new Date(job.event_date+"T12:00").toLocaleDateString("pt-BR"):"Data a definir"} · {job.status}</p></div><p className="font-bold">{money(Number(job.paid_amount))} de {money(Number(job.total))}</p></div><div className="mt-6 grid gap-2 sm:grid-cols-2">{job.service_job_tasks?.map((task:Record<string,unknown>)=><p key={String(task.id)} className={`rounded-lg p-3 ${task.done?"bg-green-950 text-green-300":"bg-neutral-900 text-neutral-400"}`}>{task.done?"✓":"○"} {String(task.title)}</p>)}</div>{job.service_job_files?.filter((file:Record<string,unknown>)=>file.visible_to_client).map((file:Record<string,unknown>)=><a key={String(file.id)} href={String(file.url)} className="mt-3 block text-red-500">Baixar {String(file.name)} →</a>)}</article>)}{!jobs?.length&&<p className="rounded-xl border border-neutral-800 p-5 text-neutral-400">Nenhum trabalho confirmado ainda.</p>}</div>
 <h2 className="mb-4 mt-10 text-2xl font-black">Pedidos de orçamento</h2><div className="grid gap-3">{requests?.map(row=><article key={row.id} className="rounded-xl border border-neutral-800 p-5"><b>#{row.protocol} · {serviceBySlug(row.service_slug)?.name}</b><p className="mt-1 text-neutral-400">Status: {row.status}</p><details className="mt-4"><summary className="cursor-pointer rounded-lg bg-neutral-800 px-4 py-3 font-bold">Abrir solicitação</summary><div className="grid gap-2 rounded-b-lg bg-neutral-950 p-4 text-sm text-neutral-300 sm:grid-cols-2"><p><b>Pacote:</b> {row.package_slug||"A definir"}</p><p><b>Data:</b> {row.event_date?new Date(row.event_date+"T12:00").toLocaleDateString("pt-BR"):"A definir"}</p><p><b>Cidade:</b> {row.city||"Não informada"}</p><p><b>Local:</b> {row.venue||"Não informado"}</p><p><b>Participantes:</b> {row.guests||"Não informado"}</p><p><b>Orçamento previsto:</b> {row.budget?money(Number(row.budget)):"Não informado"}</p>{row.notes&&<p className="sm:col-span-2"><b>Detalhes:</b> {row.notes}</p>}<a href={`https://wa.me/5519999516802?text=${encodeURIComponent(`Olá! Gostaria de falar sobre meu orçamento #${row.protocol}.`)}`} target="_blank" rel="noreferrer" className="mt-2 rounded-lg bg-green-700 px-4 py-3 text-center font-bold sm:col-span-2">Falar com a M&M no WhatsApp</a></div></details></article>)}{!requests?.length&&<p className="text-neutral-500">Nenhuma solicitação vinculada à sua conta.</p>}</div></div></main>
}
