import { requireUser } from "@/lib/auth";
import { supabaseAdmin } from "@/lib/supabaseAdmin";
import { money, serviceBySlug } from "@/lib/service-catalog";
import {BalancePaymentButton} from "@/components/services/BalancePaymentButton";

export default async function ContractsPage(){
 const user=await requireUser();
 const[{data:requests},{data:jobs}]=await Promise.all([supabaseAdmin.from("service_requests").select("*").eq("user_id",user.id).order("created_at",{ascending:false}),supabaseAdmin.from("service_jobs").select("*,service_job_tasks(*),service_job_files(*),service_activity(*),service_contracts(id,token,title,status,accepted_at),service_galleries(id,slug,title,access_token,published,expires_at),service_payments(id,kind,amount,status,paid_at)").eq("client_user_id",user.id).order("event_date",{ascending:true})]);
 return <main className="min-h-screen bg-black px-4 pb-24 pt-32 text-white"><div className="mx-auto max-w-5xl"><p className="font-bold uppercase tracking-widest text-red-500">Portal do cliente</p><h1 className="mt-2 text-4xl font-black">Minhas contratações</h1><h2 className="mb-4 mt-10 text-2xl font-black">Trabalhos em andamento</h2><div className="grid gap-5">{jobs?.map(job=>{const balance=Math.max(0,Number(job.total)-Number(job.paid_amount)),activities=[...(job.service_activity||[])].sort((a:Record<string,unknown>,b:Record<string,unknown>)=>String(b.created_at).localeCompare(String(a.created_at)));return <article key={job.id} className="rounded-2xl border border-neutral-800 bg-neutral-950 p-6"><div className="flex flex-wrap justify-between gap-4"><div><h3 className="text-2xl font-black">{job.title}</h3><p className="text-neutral-400">{job.event_date?new Date(job.event_date+"T12:00").toLocaleDateString("pt-BR"):"Data a definir"} · {job.status}</p></div><div className="text-right"><p className="font-bold">{money(Number(job.paid_amount))} de {money(Number(job.total))}</p><div className="mt-3"><BalancePaymentButton jobId={job.id} balance={balance}/></div></div></div><div className="mt-6 grid gap-2 sm:grid-cols-2">{job.service_job_tasks?.map((task:Record<string,unknown>)=><p key={String(task.id)} className={`rounded-lg p-3 ${task.done?"bg-green-950 text-green-300":"bg-neutral-900 text-neutral-400"}`}>{task.done?"✓":"○"} {String(task.title)}</p>)}</div><div className="mt-6 flex flex-wrap gap-3">{job.service_contracts?.map((c:Record<string,unknown>)=><a key={String(c.id)} href={`/contrato/${c.token}`} className="rounded-lg bg-white px-4 py-3 font-bold text-black">Contrato · {String(c.status)}</a>)}{job.service_galleries?.filter((g:Record<string,unknown>)=>g.published).map((g:Record<string,unknown>)=><a key={String(g.id)} href={`/galeria/${g.slug}?chave=${g.access_token}`} className="rounded-lg bg-red-600 px-4 py-3 font-bold">Abrir galeria privada</a>)}</div>{activities.length>0&&<details className="mt-6"><summary className="cursor-pointer font-bold">Linha do tempo do trabalho</summary><ol className="mt-3 space-y-2 border-l border-red-800 pl-5">{activities.filter((a:Record<string,unknown>)=>a.visible_to_client).map((a:Record<string,unknown>)=><li key={String(a.id)}><b>{String(a.title)}</b><small className="block text-neutral-500">{new Date(String(a.created_at)).toLocaleString("pt-BR")}</small></li>)}</ol></details>}{job.service_job_files?.filter((file:Record<string,unknown>)=>file.visible_to_client).map((file:Record<string,unknown>)=><a key={String(file.id)} href={String(file.url)} className="mt-3 block text-red-500">Baixar {String(file.name)} →</a>)}</article>})}{!jobs?.length&&<p className="rounded-xl border border-neutral-800 p-5 text-neutral-400">Nenhum trabalho confirmado ainda.</p>}</div>
 <h2 className="mb-4 mt-10 text-2xl font-black">Pedidos de orçamento</h2><div className="grid gap-3">{requests?.map(row=><article key={row.id} className="rounded-xl border border-neutral-800 p-5"><b>#{row.protocol} · {serviceBySlug(row.service_slug)?.name}</b><p className="mt-1 text-neutral-400">Status: {row.status}</p><details className="mt-4"><summary className="cursor-pointer rounded-lg bg-neutral-800 px-4 py-3 font-bold">Abrir solicitação</summary><div className="grid gap-2 rounded-b-lg bg-neutral-950 p-4 text-sm text-neutral-300 sm:grid-cols-2"><p><b>Pacote:</b> {row.package_slug||"A definir"}</p><p><b>Data:</b> {row.event_date?new Date(row.event_date+"T12:00").toLocaleDateString("pt-BR"):"A definir"}</p><p><b>Cidade:</b> {row.city||"Não informada"}</p><p><b>Local:</b> {row.venue||"Não informado"}</p><p><b>Participantes:</b> {row.guests||"Não informado"}</p><p><b>Orçamento previsto:</b> {row.budget?money(Number(row.budget)):"Não informado"}</p>{row.notes&&<p className="sm:col-span-2"><b>Detalhes:</b> {row.notes}</p>}<a href={`https://wa.me/5519999516802?text=${encodeURIComponent(`Olá! Gostaria de falar sobre meu orçamento #${row.protocol}.`)}`} target="_blank" rel="noreferrer" className="mt-2 rounded-lg bg-green-700 px-4 py-3 text-center font-bold sm:col-span-2">Falar com a M&M no WhatsApp</a></div></details></article>)}{!requests?.length&&<p className="text-neutral-500">Nenhuma solicitação vinculada à sua conta.</p>}</div></div></main>
}
