"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
type Coupon = { id: string; code: string; kind: string; value: number; uses: number; max_uses?: number | null; active: boolean; events?: { name?: string } | null };
export function CouponManager({ coupons, events }: { coupons: Coupon[]; events: Array<{ id: string; name: string }> }) {
  const router = useRouter(); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage("Criando cupom…"); const formElement = event.currentTarget; const response = await fetch("/api/admin/coupons", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(formElement))) }); const data = await response.json().catch(() => ({})); setSaving(false); if (!response.ok) return setMessage(data.error || "Não foi possível criar o cupom."); formElement.reset(); setMessage("Cupom criado com sucesso."); router.refresh(); }
  async function toggle(coupon: Coupon) { const response = await fetch(`/api/admin/coupons/${coupon.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ active: !coupon.active }) }); const data = await response.json().catch(() => ({})); setMessage(response.ok ? `Cupom ${coupon.active ? "desativado" : "ativado"}.` : data.error || "Falha ao atualizar cupom."); if (response.ok) router.refresh(); }
  return <div className="space-y-8"><form onSubmit={create} className="grid gap-3 rounded-xl border border-neutral-800 bg-neutral-900 p-4 sm:p-5 md:grid-cols-2 xl:grid-cols-3"><input name="code" required placeholder="Código" className="min-w-0 rounded bg-black px-3 py-3 uppercase"/><select name="kind" className="min-w-0 rounded bg-black px-3 py-3"><option value="percent">Percentual</option><option value="fixed">Valor fixo</option></select><input name="value" required type="number" min="0.01" step="0.01" placeholder="Valor" className="min-w-0 rounded bg-black px-3 py-3"/><input name="max_uses" type="number" min="1" placeholder="Limite de usos" className="min-w-0 rounded bg-black px-3 py-3"/><select name="event_id" className="min-w-0 rounded bg-black px-3 py-3"><option value="">Todos os eventos</option>{events.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button disabled={saving} className="rounded bg-red-600 px-4 py-3 font-bold disabled:opacity-50">{saving ? "Criando…" : "Criar cupom"}</button>{message && <p className={`rounded-lg p-3 text-sm md:col-span-2 xl:col-span-3 ${message.includes("sucesso") || message.includes("ativado") ? "bg-green-950 text-green-200" : "bg-red-950 text-red-200"}`} role="status">{message}</p>}</form><div className="grid gap-3">{coupons.map(coupon => <div key={coupon.id} className="flex flex-col gap-4 rounded-xl border border-neutral-800 bg-neutral-900 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><b>{coupon.code}</b><p className="break-words text-sm text-neutral-400">{coupon.kind === "percent" ? `${coupon.value}%` : `R$ ${coupon.value}`} · {coupon.uses}/{coupon.max_uses || "∞"} usos · {coupon.events?.name || "todos os eventos"}</p></div><button onClick={() => toggle(coupon)} className="rounded bg-neutral-700 px-4 py-2 sm:shrink-0">{coupon.active ? "Desativar" : "Ativar"}</button></div>)}</div></div>;
}
