"use client";
import { useEffect, useState } from "react";
type Row = { id: string; min_quantity: number; unit_price: number; label: string; active: boolean };
export default function PricingManager() {
  const [rows, setRows] = useState<Row[]>([]); const [form, setForm] = useState({ min_quantity: "", unit_price: "", label: "" }); const [message, setMessage] = useState("");
  async function load() { const response = await fetch("/api/admin/pricing"); const data = await response.json(); setRows(data.packages || []); }
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  async function save() { setMessage(""); const response = await fetch("/api/admin/pricing", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) return setMessage(data.error || "Não foi possível salvar"); setForm({ min_quantity: "", unit_price: "", label: "" }); setMessage("Pacote salvo."); await load(); }
  async function toggle(row: Row) { await fetch(`/api/admin/pricing/${row.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ active: !row.active }) }); await load(); }
  return <div className="space-y-6"><div className="grid gap-3 rounded-xl border border-neutral-800 bg-neutral-900 p-5 md:grid-cols-[140px_160px_1fr_auto]"><input type="number" min="1" placeholder="Qtd. mínima" value={form.min_quantity} onChange={e => setForm({ ...form, min_quantity: e.target.value })} className="rounded bg-black px-3 py-2" /><input type="number" min="0.01" step="0.01" placeholder="Preço unitário" value={form.unit_price} onChange={e => setForm({ ...form, unit_price: e.target.value })} className="rounded bg-black px-3 py-2" /><input placeholder="Nome do pacote" value={form.label} onChange={e => setForm({ ...form, label: e.target.value })} className="rounded bg-black px-3 py-2" /><button type="button" onClick={save} className="rounded bg-red-600 px-5 py-2 font-bold">Salvar</button>{message && <p className="md:col-span-4 text-sm text-neutral-300">{message}</p>}</div><div className="overflow-hidden rounded-xl border border-neutral-800">{rows.map(row => <div key={row.id} className="flex items-center justify-between gap-4 border-b border-neutral-800 bg-neutral-900 p-4 last:border-0"><div><b>{row.label}</b><p className="text-sm text-neutral-400">A partir de {row.min_quantity} foto(s) · R$ {Number(row.unit_price).toFixed(2).replace(".", ",")} cada</p></div><button type="button" onClick={() => toggle(row)} className={`rounded px-4 py-2 font-bold ${row.active ? "bg-green-700" : "bg-neutral-700"}`}>{row.active ? "Ativo" : "Inativo"}</button></div>)}</div></div>;
}
