"use client";
import {useEffect,useMemo,useState} from "react";
type Order={id:string;name?:string;whatsapp?:string;review_token:string;review_requested_at?:string;photographers:string[]};
type Review={id:string;target_type:string;photographer_id?:string;customer_name:string;rating:number;comment?:string;published:boolean};
type Person={id:string;full_name?:string;email:string};
const cleanPhone=(value="")=>{const digits=value.replace(/\D/g,"");return digits.startsWith("55")?digits:`55${digits}`};
export function ReviewManager(){
 const[orders,setOrders]=useState<Order[]>([]),[reviews,setReviews]=useState<Review[]>([]),[people,setPeople]=useState<Person[]>([]),[tab,setTab]=useState<"reviews"|"requests">("reviews"),[message,setMessage]=useState(""),[template,setTemplate]=useState("Olá, {nome}! 📸 Esperamos que tenha gostado das suas fotos da M&M. Conte como foi sua experiência:\n\n{link}\n\nLeva menos de um minuto e ajuda muito nosso trabalho. Obrigado! ❤️");
 async function load(){const r=await fetch("/api/admin/reviews"),d=await r.json();setOrders(d.orders||[]);setReviews(d.reviews||[]);setPeople(d.people||[])}
 useEffect(()=>{void load()},[]);const names=useMemo(()=>new Map(people.map(p=>[p.id,p.full_name||p.email])),[people]);
 async function patch(body:object){const r=await fetch("/api/admin/reviews",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});setMessage(r.ok?"Atualizado.":"Não foi possível atualizar.");await load()}
 async function remove(id:string){if(!confirm("Excluir esta avaliação?"))return;await fetch(`/api/admin/reviews?id=${id}`,{method:"DELETE"});await load()}
 function ask(order:Order,destination:"choice"|"studio"|"photographer",photographerId=""){const suffix=destination==="studio"?"?destino=studio":destination==="photographer"?`?destino=photographer&fotografo=${photographerId}`:"",link=`${window.location.origin}/avaliar/${order.review_token}${suffix}`,text=template.replaceAll("{nome}",order.name||"cliente").replaceAll("{link}",link);window.open(`https://wa.me/${cleanPhone(order.whatsapp)}?text=${encodeURIComponent(text)}`,"_blank","noopener,noreferrer");void patch({kind:"requested",id:order.id})}
 const average=reviews.length?reviews.reduce((sum,row)=>sum+row.rating,0)/reviews.length:0;
 return <div><div className="mb-6 grid gap-3 sm:grid-cols-3"><Metric label="Avaliações" value={String(reviews.length)}/><Metric label="Nota média" value={`${average.toFixed(1)} ★`} yellow/><Metric label="Aguardando moderação" value={String(reviews.filter(row=>!row.published).length)}/></div><div className="mb-6 flex gap-2"><button onClick={()=>setTab("reviews")} className={`rounded-lg px-4 py-3 font-bold ${tab==="reviews"?"bg-red-600":"bg-neutral-800"}`}>Avaliações</button><button onClick={()=>setTab("requests")} className={`rounded-lg px-4 py-3 font-bold ${tab==="requests"?"bg-green-700":"bg-neutral-800"}`}>Solicitar pelo WhatsApp</button></div>{tab==="reviews"?<div className="space-y-3">{reviews.map(row=><article key={row.id} className="rounded-xl border border-neutral-800 bg-neutral-900 p-5"><div className="flex flex-wrap justify-between gap-3"><div><b>{row.customer_name}</b><p className="text-yellow-400">{"★".repeat(row.rating)}{"☆".repeat(5-row.rating)}</p><small className="text-neutral-500">{row.target_type==="studio"?"M&M Fotografias":names.get(row.photographer_id||"")||"Fotógrafo"} · compra verificada</small></div><span className={row.published?"text-green-400":"text-amber-400"}>{row.published?"Publicada":"Aguardando"}</span></div><p className="my-4 text-neutral-300">{row.comment||"Sem comentário."}</p><div className="flex gap-2"><button onClick={()=>patch({id:row.id,published:!row.published})} className="rounded bg-red-700 px-3 py-2">{row.published?"Ocultar":"Publicar"}</button><button onClick={()=>remove(row.id)} className="rounded bg-neutral-700 px-3 py-2">Excluir</button></div></article>)}{!reviews.length&&<p className="rounded-xl bg-neutral-900 p-6 text-neutral-400">Nenhuma avaliação recebida ainda.</p>}</div>:<div><label className="mb-6 block rounded-xl border border-neutral-800 bg-neutral-900 p-5"><b>Mensagem padrão editável</b><textarea rows={7} value={template} onChange={e=>setTemplate(e.target.value)} className="mt-3 w-full rounded-lg bg-black p-4"/><small className="text-neutral-500">Use {"{nome}"} e {"{link}"}; serão preenchidos automaticamente.</small></label><div className="space-y-3">{orders.map(order=><OrderInvite key={order.id} order={order} people={people} ask={ask}/>)}</div></div>}{message&&<p className="mt-4" aria-live="polite">{message}</p>}</div>
}
function Metric({label,value,yellow=false}:{label:string;value:string;yellow?:boolean}){return <div className="rounded-xl bg-neutral-900 p-5"><span className="text-neutral-400">{label}</span><b className={`block text-3xl ${yellow?"text-yellow-400":""}`}>{value}</b></div>}
function OrderInvite({order,people,ask}:{order:Order;people:Person[];ask:(order:Order,destination:"choice"|"studio"|"photographer",photographerId?:string)=>void}){const[selected,setSelected]=useState("");const eligible=people.filter(person=>order.photographers?.includes(person.id));return <article className="rounded-xl border border-neutral-800 bg-neutral-900 p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><b>{order.name||"Cliente"}</b><p className="text-sm text-neutral-400">{order.whatsapp||"Sem WhatsApp"} · pedido #{order.id.slice(0,8).toUpperCase()}</p><small className={order.review_requested_at?"text-green-400":"text-neutral-500"}>{order.review_requested_at?"Convite já enviado":"Ainda não solicitado"}</small></div><div className="flex flex-wrap gap-2"><button disabled={!order.whatsapp} onClick={()=>ask(order,"choice")} className="rounded-lg bg-green-700 px-3 py-2 font-bold disabled:opacity-40">Cliente escolhe</button><button disabled={!order.whatsapp} onClick={()=>ask(order,"studio")} className="rounded-lg bg-red-700 px-3 py-2 font-bold disabled:opacity-40">Avaliar M&M</button></div></div>{eligible.length>0&&<div className="mt-4 flex flex-wrap gap-2"><select value={selected} onChange={e=>setSelected(e.target.value)} className="min-w-52 flex-1 rounded-lg bg-black p-3"><option value="">Escolha o profissional</option>{eligible.map(person=><option key={person.id} value={person.id}>{person.full_name||person.email}</option>)}</select><button disabled={!order.whatsapp||!selected} onClick={()=>ask(order,"photographer",selected)} className="rounded-lg bg-yellow-600 px-4 py-2 font-bold text-black disabled:opacity-40">Avaliar profissional</button></div>}</article>}
