"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { money, serviceBySlug } from "@/lib/service-catalog";

type Row = Record<string, string | number | null | undefined>;
type StudioData = { requests: Row[]; proposals: Row[]; jobs: Row[] };
const EMPTY: StudioData = { requests: [], proposals: [], jobs: [] };

export function StudioManager() {
  const [data,setData]=useState<StudioData>(EMPTY),[loading,setLoading]=useState(true),[tab,setTab]=useState("requests");
  async function load(){const response=await fetch("/api/admin/studio",{cache:"no-store"});setData(await response.json());setLoading(false)}
  useEffect(()=>{fetch("/api/admin/studio",{cache:"no-store"}).then(response=>response.json()).then(setData).finally(()=>setLoading(false))},[]);
  async function patch(kind:string,id:string,status:string){await fetch("/api/admin/studio",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,id,status})});await load()}
  async function proposal(row:Row){const suggested=row.package_slug==="essencial"?"1200":row.package_slug==="elegance"?"2400":row.package_slug==="lux"?"3800":"0",total=Number(prompt("Valor total da proposta",suggested)||0);if(!total)return;const deposit=Number(prompt("Valor do sinal",String(total*.3))||0),response=await fetch("/api/admin/studio",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"proposal",requestId:row.id,title:`Proposta ${serviceBySlug(String(row.service_slug))?.name||row.service_slug}`,description:`Cobertura fotográfica para ${row.client_name}`,items:[{description:"Serviço fotográfico",quantity:1,price:total}],total,depositAmount:deposit,terms:"Reserva confirmada após pagamento do sinal. Data e escopo sujeitos à disponibilidade e ao aceite desta proposta."})}),result=await response.json();if(response.ok){await navigator.clipboard.writeText(`${location.origin}/proposta/${result.token}`);alert("Proposta criada e link copiado!")}else alert(result.error);await load()}
  async function job(row:Row){const proposal=data.proposals.find(item=>item.request_id===row.id&&item.status==="accepted")||data.proposals.find(item=>item.request_id===row.id),payload={kind:"job",requestId:row.id,proposalId:proposal?.id,total:proposal?.total||0,force:false};let response=await fetch("/api/admin/studio",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),result=await response.json();if(response.status===409&&confirm(`${result.error}\n\nDeseja criar mesmo assim?`)){response=await fetch("/api/admin/studio",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...payload,force:true})});result=await response.json()}alert(response.ok?"Trabalho criado com checklist.":result.error);await load()}
  async function schedule(row:Row){const eventDate=prompt("Data (AAAA-MM-DD)",String(row.event_date||""));if(!eventDate)return;const start_time=prompt("Início (HH:MM)",String(row.start_time||"09:00")),end_time=prompt("Fim (HH:MM)",String(row.end_time||"12:00"));const r=await fetch("/api/admin/studio",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"job",id:row.id,event_date:eventDate,start_time,end_time})}),d=await r.json();alert(r.ok?"Agenda atualizada sem conflitos.":d.error);await load()}
  async function reminders(){const r=await fetch("/api/admin/studio/reminders",{method:"POST"}),d=await r.json();alert(r.ok?`${d.sent} lembrete(s) enviado(s).`:d.error)}
  if(loading)return <p>Carregando estúdio…</p>;
  return <div><div className="mb-6 flex flex-wrap gap-2">{[["requests","Solicitações"],["proposals","Propostas"],["jobs","Agenda e trabalhos"]].map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`rounded-lg px-4 py-3 font-bold ${tab===id?"bg-red-600":"bg-neutral-800"}`}>{label}</button>)}</div>
    {tab==="requests"&&<div className="grid gap-4">{data.requests.map(row=><article key={String(row.id)} className="rounded-2xl border border-neutral-800 bg-neutral-950 p-5"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs font-bold text-red-500">#{row.protocol} · {row.status}</p><h2 className="mt-1 text-xl font-black">{row.client_name} · {serviceBySlug(String(row.service_slug))?.name}</h2><p className="text-neutral-400">{row.package_slug||"Personalizado"} · {row.event_date?new Date(String(row.event_date)+"T12:00").toLocaleDateString("pt-BR"):"Data a definir"} · {row.city||"Cidade a definir"}</p><p className="mt-2">{row.notes}</p></div><div className="flex flex-wrap items-start gap-2"><a className="rounded-lg bg-green-700 px-3 py-2 font-bold" target="_blank" href={`https://wa.me/55${row.whatsapp}?text=${encodeURIComponent(`Olá, ${row.client_name}! Recebemos seu pedido de orçamento #${row.protocol} na M&M Fotografias.`)}`}>WhatsApp</a><button onClick={()=>proposal(row)} className="rounded-lg bg-red-600 px-3 py-2 font-bold">Criar proposta</button><button onClick={()=>job(row)} className="rounded-lg bg-neutral-700 px-3 py-2 font-bold">Criar trabalho</button><select value={String(row.status)} onChange={event=>patch("request",String(row.id),event.target.value)} className="rounded-lg bg-neutral-800 p-2">{["new","contacted","qualifying","proposal","approved","declined","booked","completed","cancelled"].map(status=><option key={status}>{status}</option>)}</select></div></div></article>)}{!data.requests.length&&<p>Nenhuma solicitação ainda.</p>}</div>}
    {tab==="proposals"&&<div className="grid gap-4">{data.proposals.map(row=><article key={String(row.id)} className="rounded-xl border border-neutral-800 p-5"><h2 className="font-black">{row.title}</h2><p>{money(Number(row.total))} · sinal {money(Number(row.deposit_amount))} · {row.status}</p><Link className="mt-3 inline-block text-red-500" href={`/proposta/${row.token}`}>Abrir proposta →</Link></article>)}</div>}
    {tab==="jobs"&&<div><button onClick={reminders} className="mb-4 rounded-xl bg-white px-4 py-3 font-black text-black">🔔 Enviar lembretes dos próximos 7 dias</button><div className="grid gap-4">{data.jobs.map(row=><article key={String(row.id)} className="rounded-xl border border-neutral-800 p-5"><h2 className="text-xl font-black">{row.title}</h2><p className="text-neutral-400">{row.event_date?new Date(String(row.event_date)+"T12:00").toLocaleDateString("pt-BR"):"Sem data"} {row.start_time?`· ${String(row.start_time).slice(0,5)}–${String(row.end_time||"").slice(0,5)}`:""} · {row.city||"Local a definir"}</p><p className="mt-2">{money(Number(row.paid_amount))} pagos de {money(Number(row.total))}</p><div className="mt-3 flex flex-wrap gap-2"><select value={String(row.status)} onChange={event=>patch("job",String(row.id),event.target.value)} className="rounded-lg bg-neutral-800 p-2">{["scheduled","preparing","shooting","editing","review","delivered","completed","cancelled"].map(status=><option key={status}>{status}</option>)}</select><button onClick={()=>schedule(row)} className="rounded-lg bg-neutral-800 px-4 py-2 font-bold">Ajustar agenda</button><Link href="/admin/contracts" className="rounded-lg bg-neutral-800 px-4 py-2 font-bold">Contrato</Link><Link href="/admin/galleries" className="rounded-lg bg-red-700 px-4 py-2 font-bold">Galeria</Link></div></article>)}</div></div>}
  </div>
}
