"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
type Member = { id:string; email:string; full_name?:string; role:string; commission_rate:number; bio?:string; instagram_handle?:string; avatar_url?:string; public_profile?:boolean };
const blank = { email:"", role:"admin", commissionRate:"0", bio:"", instagramHandle:"", avatarUrl:"", publicProfile:false };
export default function TeamManager() {
  const [members,setMembers]=useState<Member[]>([]); const [form,setForm]=useState(blank); const [message,setMessage]=useState("");
  async function load(){ const response=await fetch("/api/admin/team"); const data=await response.json(); setMembers(data.members||[]); if(!response.ok)setMessage(data.error); }
  useEffect(()=>{void load()},[]);
  async function save(event:React.FormEvent){event.preventDefault();const response=await fetch("/api/admin/team",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const data=await response.json();setMessage(response.ok?"Cadastro profissional atualizado.":data.error||"Erro.");if(response.ok){setForm(blank);await load();}}
  function edit(member:Member){setForm({email:member.email,role:member.role,commissionRate:String(member.commission_rate||0),bio:member.bio||"",instagramHandle:member.instagram_handle||"",avatarUrl:member.avatar_url||"",publicProfile:Boolean(member.public_profile)});window.scrollTo({top:0,behavior:"smooth"});}
  return <div className="space-y-7"><form onSubmit={save} className="grid gap-3 rounded-xl border border-neutral-800 bg-neutral-900 p-5 md:grid-cols-2">
    <input required type="email" placeholder="E-mail da conta" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="rounded bg-black p-3"/>
    <select value={form.role} onChange={e=>setForm({...form,role:e.target.value})} className="rounded bg-black p-3"><option value="admin">Administrador</option><option value="support">Atendimento</option><option value="photographer">Fotógrafo</option><option value="client">Cliente</option></select>
    {form.role==="photographer"&&<><input type="number" min="0" max="100" step="0.01" value={form.commissionRate} onChange={e=>setForm({...form,commissionRate:e.target.value})} className="rounded bg-black p-3" placeholder="Comissão %"/><input value={form.instagramHandle} onChange={e=>setForm({...form,instagramHandle:e.target.value})} className="rounded bg-black p-3" placeholder="Instagram (sem @)"/><input value={form.avatarUrl} onChange={e=>setForm({...form,avatarUrl:e.target.value})} className="rounded bg-black p-3 md:col-span-2" placeholder="URL da foto de perfil"/><textarea value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})} className="min-h-24 rounded bg-black p-3 md:col-span-2" placeholder="Biografia pública (até 500 caracteres)"/><label className="flex items-center gap-3"><input type="checkbox" checked={form.publicProfile} onChange={e=>setForm({...form,publicProfile:e.target.checked})}/> Publicar perfil profissional</label></>}
    <button className="rounded bg-red-600 px-5 py-3 font-bold md:col-span-2">Salvar cadastro</button>{message&&<p className="md:col-span-2 text-sm">{message}</p>}
  </form><div className="overflow-x-auto rounded-xl border border-neutral-800"><table className="w-full min-w-[720px] text-left"><thead className="bg-neutral-900 text-neutral-400"><tr><th className="p-4">Pessoa</th><th>Cargo</th><th>Comissão</th><th>Perfil</th><th>Ação</th></tr></thead><tbody>{members.map(member=><tr key={member.id} className="border-t border-neutral-800"><td className="p-4"><b>{member.full_name||"Sem nome"}</b><p className="text-sm text-neutral-500">{member.email}</p></td><td>{member.role}</td><td>{member.role==="photographer"?`${Number(member.commission_rate).toFixed(2)}%`:"—"}</td><td>{member.public_profile?<Link className="text-green-400 underline" href={`/fotografos/${member.id}`} target="_blank">Publicado</Link>:"Privado"}</td><td>{member.role!=="owner"&&<button type="button" onClick={()=>edit(member)} className="rounded bg-neutral-800 px-3 py-2 hover:bg-neutral-700">Editar</button>}</td></tr>)}</tbody></table></div></div>;
}
