"use client";
import { useEffect, useState } from "react";
type InstallPrompt = Event & { prompt: () => Promise<void>; userChoice: Promise<{ outcome: string }> };
export function AppExperience() {
  const [installPrompt, setInstallPrompt] = useState<InstallPrompt | null>(null); const [offline, setOffline] = useState(false); const [updateReady, setUpdateReady] = useState(false);
  useEffect(() => { setOffline(!navigator.onLine); const online = () => setOffline(false); const offlineHandler = () => setOffline(true); const beforeInstall = (event: Event) => { event.preventDefault(); setInstallPrompt(event as InstallPrompt); }; window.addEventListener("online", online); window.addEventListener("offline", offlineHandler); window.addEventListener("beforeinstallprompt", beforeInstall); if ("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js").then(registration => { registration.addEventListener("updatefound", () => { const worker = registration.installing; worker?.addEventListener("statechange", () => { if (worker.state === "installed" && navigator.serviceWorker.controller) setUpdateReady(true); }); }); }).catch(() => undefined); return () => { window.removeEventListener("online", online); window.removeEventListener("offline", offlineHandler); window.removeEventListener("beforeinstallprompt", beforeInstall); }; }, []);
  if (!offline && !updateReady && !installPrompt) return null;
  return <div className="fixed bottom-[calc(1rem+env(safe-area-inset-bottom))] left-1/2 z-[180] flex w-[calc(100%-2rem)] max-w-md -translate-x-1/2 items-center justify-between gap-3 rounded-xl border border-neutral-700 bg-neutral-950/95 p-3 text-sm text-white shadow-2xl backdrop-blur">{offline ? <span>Você está offline. O que já abriu pode continuar disponível.</span> : updateReady ? <span>Uma versão nova do site está disponível.</span> : <span>Instale a M&M como aplicativo neste aparelho.</span>}{updateReady && <button onClick={() => location.reload()} className="shrink-0 rounded-lg bg-red-600 px-3 py-2 font-bold">Atualizar</button>}{installPrompt && !updateReady && !offline && <button onClick={async () => { await installPrompt.prompt(); await installPrompt.userChoice; setInstallPrompt(null); }} className="shrink-0 rounded-lg bg-red-600 px-3 py-2 font-bold">Instalar</button>}</div>;
}
