"use client";
import {useEffect,useState} from "react";
function decode(value:string){const padding="=".repeat((4-value.length%4)%4),raw=atob((value+padding).replace(/-/g,"+").replace(/_/g,"/"));return Uint8Array.from([...raw].map(char=>char.charCodeAt(0)))}
async function register(subscription:PushSubscription){const json=subscription.toJSON();return fetch("/api/push/subscription",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(json)})}
export function PushNotifications(){
 const[available,setAvailable]=useState(false),[enabled,setEnabled]=useState(false),[message,setMessage]=useState(""),[testing,setTesting]=useState(false);
 useEffect(()=>{if(!("serviceWorker"in navigator)||!("PushManager"in window))return;fetch("/api/push/subscription").then(r=>r.json()).then(async data=>{if(!data.authenticated||!data.configured)return;setAvailable(true);const registration=await navigator.serviceWorker.ready,subscription=await registration.pushManager.getSubscription();if(subscription){const response=await register(subscription);setEnabled(response.ok)}}).catch(()=>undefined)},[]);
 async function enable(){try{if(Notification.permission==="denied"){setMessage("Notificações bloqueadas. Libere a M&M nas configurações do navegador.");return}const config=await fetch("/api/push/subscription").then(r=>r.json()),registration=await navigator.serviceWorker.ready,existing=await registration.pushManager.getSubscription(),subscription=existing||await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:decode(config.publicKey)}),r=await register(subscription);setEnabled(r.ok);setMessage(r.ok?"Notificações ativadas e vinculadas à sua conta.":"Não foi possível registrar este aparelho.")}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível ativar.")}}
 async function test(){setTesting(true);setMessage("Enviando teste…");const r=await fetch("/api/push/subscription",{method:"PATCH"}),d=await r.json().catch(()=>({}));setMessage(r.ok?`Teste enviado para ${d.sent} aparelho(s).`:d.configured===false?"As chaves de notificação não estão configuradas na Vercel.":"Nenhum aparelho aceitou o teste. Reative as notificações nas configurações.");setTesting(false)}
 if(!available)return null;
 return <div className="fixed bottom-[calc(5.25rem+env(safe-area-inset-bottom))] right-4 z-[170] flex max-w-[calc(100vw-2rem)] flex-col items-end gap-2 sm:bottom-5"><div className="flex flex-wrap justify-end gap-2">{enabled&&<button type="button" disabled={testing} onClick={test} className="rounded-full border border-neutral-700 bg-neutral-950/95 px-4 py-3 text-sm font-bold text-white shadow-xl disabled:opacity-50">{testing?"Testando…":"Testar 🔔"}</button>}<button type="button" disabled={enabled} onClick={enable} className={`rounded-full border px-4 py-3 text-sm font-bold shadow-2xl backdrop-blur ${enabled?"border-green-800 bg-green-950/90 text-green-300":"border-red-800 bg-neutral-950/95 text-white"}`}>{enabled?"🔔 Notificações ativas":"🔔 Ativar notificações"}</button></div>{message&&<p className="max-w-sm rounded-lg bg-black p-2 text-xs text-white shadow-xl" aria-live="polite">{message}</p>}</div>
}
