"use client";
import { useEffect, useState } from "react";
import QRCode from "qrcode";
import Image from "next/image";

export function EventShareTools({ title, initialMessage }: { title: string; initialMessage?: string | null }) {
  const [url, setUrl] = useState(""); const [qr, setQr] = useState(""); const [copied, setCopied] = useState(false); const [showWhatsApp, setShowWhatsApp] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { const current = window.location.href; const timer = window.setTimeout(() => setUrl(current), 0); void QRCode.toDataURL(current, { width: 220, margin: 1, color: { dark: "#000000", light: "#ffffff" } }).then(setQr); return () => window.clearTimeout(timer); }, []);
  async function share() { if (navigator.share) await navigator.share({ title, url }); else { await navigator.clipboard.writeText(url); setCopied(true); } }
  function openWhatsAppEditor() { const saved = localStorage.getItem(`mm-share-message:${title}`); setMessage(saved || initialMessage || `Olá! As fotos do ${title} já estão disponíveis. Acesse o álbum para encontrar e comprar suas fotos:`); setShowWhatsApp(true); }
  function sendWhatsApp() { const clean = message.trim(); localStorage.setItem(`mm-share-message:${title}`, clean); window.open(`https://wa.me/?text=${encodeURIComponent(`${clean}\n\n${url}`)}`, "_blank", "noopener,noreferrer"); setShowWhatsApp(false); }
  if (!url) return null;
  return <><div className="mt-6 flex flex-wrap items-center gap-3"><button onClick={share} className="rounded-lg bg-neutral-800 px-4 py-2 font-semibold hover:bg-neutral-700">{copied ? "Link copiado" : "Compartilhar evento"}</button><button type="button" onClick={openWhatsAppEditor} className="rounded-lg bg-green-700 px-4 py-2 font-semibold hover:bg-green-600">Enviar pelo WhatsApp</button><details className="relative"><summary className="cursor-pointer rounded-lg bg-neutral-800 px-4 py-2 font-semibold">QR Code</summary>{qr && <div className="absolute left-0 z-20 mt-2 rounded-xl bg-white p-3 shadow-xl"><Image unoptimized src={qr} width={220} height={220} alt={`QR Code do evento ${title}`} /></div>}</details></div>{showWhatsApp && <div className="fixed inset-0 z-[100] grid place-items-center bg-black/80 p-4" role="dialog" aria-modal="true" aria-labelledby="share-title" onClick={() => setShowWhatsApp(false)}><div className="w-full max-w-xl rounded-xl border border-neutral-700 bg-neutral-900 p-6 shadow-2xl" onClick={event => event.stopPropagation()}><h2 id="share-title" className="text-2xl font-bold">Mensagem do WhatsApp</h2><p className="mt-2 text-sm text-neutral-400">Adapte a abordagem para o evento ou grupo. O link será acrescentado automaticamente.</p><textarea autoFocus rows={7} maxLength={1200} value={message} onChange={event => setMessage(event.target.value)} className="mt-5 w-full rounded-lg border border-neutral-700 bg-black p-4 text-white outline-none focus:border-green-600" /><div className="mt-2 text-right text-xs text-neutral-500">{message.length}/1200</div><div className="mt-4 flex justify-end gap-3"><button type="button" onClick={() => setShowWhatsApp(false)} className="rounded-lg bg-neutral-700 px-4 py-2 font-semibold">Cancelar</button><button type="button" disabled={!message.trim()} onClick={sendWhatsApp} className="rounded-lg bg-green-700 px-4 py-2 font-semibold disabled:opacity-50">Abrir WhatsApp</button></div></div></div>}</>;
}
