import { randomUUID } from "node:crypto";
import sharp from "sharp";
import { createClient } from "@/lib/supabase/server";
import { supabaseAdmin } from "@/lib/supabaseAdmin";
import { hasRole } from "@/lib/roles";
const BUCKET="portfolio-assets",MAX_FILES=16,MAX_BYTES=12*1024*1024;
async function photographer(){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return null;const{data:profile}=await supabase.from("profiles").select("role,roles").eq("id",user.id).maybeSingle();return hasRole(profile,["photographer"])?user:null}
const publicUrl=(path:string)=>supabaseAdmin.storage.from(BUCKET).getPublicUrl(path).data.publicUrl;
export async function GET(){const user=await photographer();if(!user)return Response.json({error:"Acesso negado."},{status:403});const{data,error}=await supabaseAdmin.from("photographer_portfolio_assets").select("*").eq("photographer_id",user.id).order("sort_order").order("created_at",{ascending:false});return error?Response.json({error:error.message},{status:500}):Response.json({assets:(data||[]).map(item=>({...item,url:publicUrl(item.storage_path)}))})}
export async function POST(request:Request){const user=await photographer();if(!user)return Response.json({error:"Acesso negado."},{status:403});const form=await request.formData(),files=form.getAll("files").filter((item):item is File=>item instanceof File&&item.size>0),category=String(form.get("category")||"Outros").slice(0,60);if(!files.length||files.length>MAX_FILES)return Response.json({error:`Selecione de 1 a ${MAX_FILES} fotos.`},{status:400});const created=[];for(const file of files){if(!file.type.startsWith("image/")||file.size>MAX_BYTES)return Response.json({error:`${file.name}: use uma imagem de até 12 MB.`},{status:400});const image=sharp(Buffer.from(await file.arrayBuffer()),{failOn:"error"}).rotate().resize({width:2400,height:2400,fit:"inside",withoutEnlargement:true}),metadata=await image.metadata(),output=await image.webp({quality:86,effort:4}).toBuffer(),path=`${user.id}/${randomUUID()}.webp`;const{error:uploadError}=await supabaseAdmin.storage.from(BUCKET).upload(path,output,{contentType:"image/webp",upsert:false});if(uploadError)return Response.json({error:uploadError.message},{status:500});const{data,error}=await supabaseAdmin.from("photographer_portfolio_assets").insert({photographer_id:user.id,storage_path:path,title:file.name.replace(/\.[^.]+$/," ").trim().slice(0,120),category,width:metadata.width,height:metadata.height}).select().single();if(error){await supabaseAdmin.storage.from(BUCKET).remove([path]);return Response.json({error:error.message},{status:500})}created.push({...data,url:publicUrl(path)})}return Response.json({assets:created},{status:201})}
export async function PATCH(request:Request){const user=await photographer();if(!user)return Response.json({error:"Acesso negado."},{status:403});const body=await request.json(),changes={title:String(body.title||"").slice(0,120),description:String(body.description||"").slice(0,500),category:String(body.category||"Outros").slice(0,60),published:Boolean(body.published),sort_order:Number(body.sortOrder)||0,updated_at:new Date().toISOString()};const{error}=await supabaseAdmin.from("photographer_portfolio_assets").update(changes).eq("id",body.id).eq("photographer_id",user.id);return error?Response.json({error:error.message},{status:500}):Response.json({ok:true})}
export async function DELETE(request:Request){const user=await photographer();if(!user)return Response.json({error:"Acesso negado."},{status:403});const{id}=await request.json(),{data}=await supabaseAdmin.from("photographer_portfolio_assets").select("storage_path").eq("id",id).eq("photographer_id",user.id).maybeSingle();if(!data)return Response.json({error:"Foto não encontrada."},{status:404});const{error}=await supabaseAdmin.from("photographer_portfolio_assets").delete().eq("id",id).eq("photographer_id",user.id);if(error)return Response.json({error:error.message},{status:500});await supabaseAdmin.storage.from(BUCKET).remove([data.storage_path]);return Response.json({ok:true})}
