"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

export default function NewEventPage() {
  const router = useRouter(); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [form, setForm] = useState({ name: "", city: "", event_date: "", slug: "", cover_image: "", published: false });
  function update(name: string, value: string | boolean) { setForm(current => ({ ...current, [name]: value })); }
  function nameChanged(value: string) { update("name", value); if (!form.slug) update("slug", value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")); }
  async function create(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(""); const response = await fetch("/api/admin/events", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); setSaving(false); if (!response.ok) return setError(data.error || "Erro ao criar evento"); router.push(`/admin/events/${data.event.id}/edit`); }
  return <main className="min-h-screen bg-black px-6 pb-20 pt-32 text-white"><form onSubmit={create} className="mx-auto max-w-2xl space-y-5 rounded-xl border border-neutral-800 bg-neutral-900 p-7"><h1 className="text-3xl font-bold">Novo evento</h1><Field label="Nome"><input required value={form.name} onChange={e => nameChanged(e.target.value)} className="input" /></Field><Field label="Cidade"><input required value={form.city} onChange={e => update("city", e.target.value)} className="input" /></Field><Field label="Data"><input required type="date" value={form.event_date} onChange={e => update("event_date", e.target.value)} className="input" /></Field><Field label="Endereço do evento (slug)"><input required value={form.slug} onChange={e => update("slug", e.target.value)} className="input" /><small className="text-neutral-400">Exemplo: encontro-rio-claro-2026</small></Field><Field label="URL da capa (opcional)"><input value={form.cover_image} onChange={e => update("cover_image", e.target.value)} className="input" /></Field><label className="flex gap-3"><input type="checkbox" checked={form.published} onChange={e => update("published", e.target.checked)} /> Publicar imediatamente</label>{error && <p className="rounded bg-red-950 p-3 text-red-200">{error}</p>}<button disabled={saving} className="w-full rounded-lg bg-red-600 py-3 font-bold disabled:opacity-50">{saving ? "Criando..." : "Criar evento"}</button></form></main>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block space-y-2"><span>{label}</span>{children}</label>; }
