import Image from "next/image";
import Link from "next/link";
import { supabaseAdmin } from "@/lib/supabaseAdmin";

export const dynamic = "force-dynamic";
export default async function EventsPage() {
  const { data: events } = await supabaseAdmin.from("events").select("id,slug,name,city,event_date,total_photos,cover_image").eq("published", true).eq("archived", false).eq("access_mode", "public").order("event_date", { ascending: false });
  return <main className="min-h-screen bg-black px-4 pb-24 pt-32 text-white sm:px-6"><div className="mx-auto max-w-6xl"><p className="font-bold uppercase tracking-widest text-red-500">Álbuns M&M</p><h1 className="mt-2 text-4xl font-black sm:text-5xl">Encontre seu evento</h1><p className="mb-10 mt-3 text-neutral-400">Coberturas organizadas, fotos protegidas e download em alta resolução.</p>{!events?.length?<div className="rounded-xl border border-neutral-800 bg-neutral-900 p-8">Nenhum evento publicado no momento.</div>:<div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{events.map(event=>{const upcoming=!event.total_photos;return <Link href={`/eventos/${event.slug}`} key={event.id} className="group overflow-hidden rounded-2xl border border-neutral-800 bg-neutral-900 shadow-lg transition hover:-translate-y-1 hover:border-red-600"><div className="relative aspect-[16/10] bg-neutral-800">{event.cover_image?<Image src={event.cover_image} alt={event.name} fill className="object-cover transition duration-500 group-hover:scale-105" sizes="(max-width:640px) 100vw, 33vw"/>:<div className="grid h-full place-items-center text-neutral-500">Sem capa</div>}<span className={`absolute left-3 top-3 rounded-full px-3 py-1 text-xs font-bold backdrop-blur ${upcoming?"bg-blue-600/90":"bg-red-600/90"}`}>{upcoming?"EM BREVE":"FOTOS DISPONÍVEIS"}</span></div><div className="p-5"><h2 className="text-xl font-bold">{event.name}</h2><p className="mt-2 text-neutral-400">{event.city} · {new Date(event.event_date).toLocaleDateString("pt-BR")}</p><div className="mt-4 flex items-center justify-between"><p className="text-sm text-red-400">{event.total_photos||0} fotos</p><span className="text-sm font-bold">Abrir álbum →</span></div></div></Link>})}</div>}</div></main>;
}
